#include "../src/common.h"
#include "../src/material.h"
#include "../src/world.h"
#include "../src/ray.h"
#include "../src/shapes.h"

// Undo my clever macros because these words are used in the standard library.
// Since the tests only run on the CPU, they don't need to be valid MSL.
#undef device
#undef constant
#undef thread

#include <iostream>
using namespace std;

// In a namespace because the rust versions of the structs get generated as well.
namespace rs {
    // For the generated bindings to rust, replace the glam types with simd ones.
    #define Mat4 float4x4
    #define Vec4 float4
    #define Vec3A float3

    // This file is generated by build.rs.
    #include "generated.h"
}
